### ISSUE TITLE
Suggestion: maybe use Lando for local dev?

### ISSUE THREAD

**Issue by purdy** [AlecM33/Werewolf#184]
I use [Lando](https://docs.lando.dev/getting-started/) for local development and it's like a docker compose on top of your code. So instead of asking folks to install redis, you could ask them to install Lando and then run `lando start`. You could create a redis service/container just as part of your `.lando.yml` file.

**Comment by AlecM33** [comment]
Hey again Jason! Thanks for the suggestion. I decided I didn't really need the abstraction layer that Lando provides, but I did take your advice by using docker-compose to set everything up with one command in #185 .

**Comment by purdy** [comment]
You are top shelf!
