### ISSUE TITLE
Creating roles sometimes creates duplicates

### ISSUE THREAD

**Issue by daveola** [AlecM33/Werewolf#20]
Using cookies to create roles, sometimes gets duplicates.

Not always reproducible.

Meredith saw like a dozen of one he created.

My situation was:

create role A
create role B
saw roles A, A, B as extras

The extra A disappeared later.

**Comment by davidme123** [comment]
This is corrected when the page is refreshed.

**Comment by AlecM33** [comment]
This was a problem with custom roles being read into the role set multiple times when a new custom role was added. It's been patched and is working correctly now.
