### ISSUE TITLE
Allow moderators to run the same game back again

### ISSUE THREAD

**Issue by daveola** [AlecM33/Werewolf#21]
Reshuffle (and start over) same game option?

~~Maybe also an "edit timer" option?~~

Edit by @AlecM33 - the start over option makes a lot of sense. Why make the host go back to the create screen and enter all the same options again. Striking through the timer and potentially opening it as a separate issue.

**Comment by davidme123** [comment]
I like "edit timer".

**Comment by AlecM33** [comment]
@daveola what's a use case for editing the timer?

**Comment by daveola** [comment]
You run a game and realize you like it but the timer was too short/long.

**Comment by daveola** [comment]
It's always nice to basically setup with the same game but be able to change anything the next time you run it.  :)

**Comment by AlecM33** [comment]
> It's always nice to basically setup with the same game but be able to change anything the next time you run it.  :)
> 

Ah, so this is in the context of restarting? As in, restart with same configuration but change one thing. Which is also a good idea.
