### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by daveola** [AlecM33/Werewolf#23]
code should be case insensitive for when it's communicated verbally

(and maybe don't have confusing things like o/0 or 1/l)

**Comment by AlecM33** [comment]
The code is case-insensitive, as well as whitespace-insensitive:

`const code = document.getElementById("code").value.toString().trim().toLowerCase();`

The second suggestion is good. I will probably just make the code numbers only

**Comment by daveola** [comment]
Interesting - we had someone who couldn't get in until they did lower case, they must have typed something else wrong at the same time, sorry I didn't test.

Then consider this an enhancement request to not have oh/zero and one/ell.
