### ISSUE TITLE
Is there a way to make a back-up of my cookies? I've entered a lot of roles and don't want to lose them.

### ISSUE THREAD

**Issue by davidme123** [AlecM33/Werewolf#27]

**Comment by AlecM33** [comment]
In whatever browser you have saved the roles in, press F12 to open up developer tools. In the console, type `localStorage` and press enter. You should see an object that has some key-value pairs in it. One of them should be `play-werewolf-custom-roles`. The value will look something like:

`[{"role":"example","team":"good","description":"example","isTypeOfWerewolf":false,"custom":true,"saved":true}...]"`

If you copy that value and save it somewhere, in the event you lose them you'd be able to manually set this property in localStorage.

**Comment by AlecM33** [comment]
In the re-design, roles can be imported and exported as a text file.
