### ISSUE TITLE
Make the basic Minion not end the game as if it were a Werewolf. It doesn't count for Parity. 

### ISSUE THREAD

**Issue by davidme123** [AlecM33/Werewolf#37]
Tricks can be pulled to make the WWs lose the game in final three with Minion, WW, Villager ending.

**Comment by AlecM33** [comment]
Is this a scenario that happened? The game shouldn't be counting minions towards parity, and should have let the game continue as if it were two villagers / one wolf. Were you using the standard set minion, or a minion of your own creation?
