### ISSUE TITLE
Game options in screen that shows a player's role and the role list.

### ISSUE THREAD

**Issue by davidme123** [AlecM33/Werewolf#42]
Things like "Private chat is allowed-Disallowed-Neighbors only" and "May players end a day phase early?" and if so, "What happens: Sleep and wolves eat, Tribunal, Reverse Tribunal, 1-2-3 Point, etc." (<with custom ideas possible) And maybe allow multiple options within the same game if mod chooses.

Get with me and I could help define these better if you choose to do it.

**Comment by davidme123** [comment]
No functionality requested, just the options shown in the "dealt card" screen.

**Comment by davidme123** [comment]
Or maybe this could be done by allowing a Custom card that displays in the screen of roles in the game, timer, etc. This custom card would be a Rules card that is not dealt to any player that shows the mod style, rules used, etc.

**Comment by AlecM33** [comment]
This will live on as #120
