### ISSUE TITLE
Condense duplicate roles in the list of alive players into one instance of the role with the appropriate number

### ISSUE THREAD

**Issue by AlecM33** [AlecM33/Werewolf#48]
For example, if there are 7 villagers, instead of displaying villager 7 times, display it once with a "7" next to it. Very relevant for larger games.

**Comment by rtmoffat** [comment]
I can take this one if you want. :)

**Comment by AlecM33** [comment]
Feel free to assign yourself the issue

**Comment by rtmoffat** [comment]
I don't think I can assign myself to Issues within this repository, only my fork of it.

**Comment by AlecM33** [comment]
I've invited you to collaborate on the project (your invite will be received via e-mail). This will allow you to open pull requests directly on the repo.

**Comment by rtmoffat** [comment]
Thanks! I'm about halfway done with this.

**Comment by rtmoffat** [comment]
Just an update. Consolidated counts are working, just working on some alignment issues and then it should be ready to go.
