### ISSUE TITLE
Part of a future Mod Mode?

### ISSUE THREAD

**Issue by davidme123** [AlecM33/Werewolf#56]
Sometimes we still forget when we are killed and click "I'm Dead" and "yes I'm dead" out of habit. If there were toggle to set the game to "No Reveal" and/or "Day Reveals Only" (tho we don't do the second option now, the option would be great and a lot of other groups use it, and it's going to prolly be a part of the next version of Ultimate Werewolf set), then maybe that toggle removes the I'm Dead button entirely...just a button that is at top maybe, somehow explicitly different that says "The Game Is Finished" for pure "No Reveal" games.

For "Day Reveals Only", there'd need to be an option for a dead player to say which type of kill it is.

**Comment by AlecM33** [comment]
In the re-design, for moderators, killing players and revealing players are two separate actions, both guarded by a confirmation. This allows built-in support for reveal or no-reveal games.
