### ISSUE TITLE
Another "mod mode" thing, maybe: Aux evil conversions

### ISSUE THREAD

**Issue by davidme123** [AlecM33/Werewolf#57]
Make the role page have an option for the creator of the game to change an Evil team red to an Evil team red with a red line around it (counts for parity) mid-game. There are tons of transformation roles that trigger on different events.

**Comment by AlecM33** [comment]
This ask is no longer applicable to the re-design - the game is ended voluntarily, so judging which roles count for parity at the current moment is up to the moderator.
