### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by janheinrichmerker** [AlecM33/Werewolf#74]
Is your code licensed? I'm Heinrich from the Computer Science student's council in Halle, Germany.
We're host and maintain a collection of online open source board and card games (https://github.com/fsrmatheinfo/spieleabend) and we would be happy to include your great app!
Have you thought about licensing your code under any open source license?

**Comment by AlecM33** [comment]
I added an MIT license. Feel free to use anything you like :) Prost!

**Comment by janheinrichmerker** [comment]
Thank you!
