### ISSUE TITLE
Game ends prematurely with custom werewolf role still alive

### ISSUE THREAD

**Issue by zorkmead** [AlecM33/Werewolf#9]
While playing last night, mod had created a deck with an evil team of Werewolf and a custom Werewolf. When the Werewolf (role chosen from standard set) died, the app ended the game and revealed the identity of the entire evil team.

**Comment by AlecM33** [comment]
There is a now a checkbox when a custom role is created to indicate it is a werewolf. These roles will be factored in when the game checks for a victory.
